# Generated by Django 5.2.6 on 2025-09-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0002_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_ru',
        ),
    ]
