# Generated by Django 5.2.6 on 2025-09-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0003_remove_review_comment_en_remove_review_comment_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_name_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_name_ru',
        ),
    ]
